name: intervention_stats
description: Une application pour suivre les interventions médicales

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.12.0
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.4.48
  datetime_picker_formfield: ^2.0.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/scout_logo.png
  - assets/images/unhcr_logo.png
