// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWDbl_4bUZG2IHDxnxPcan-eBzZtsuY0M',
    appId: '1:481214437178:web:eb621d71c88af5d4412203',
    messagingSenderId: '481214437178',
    projectId: 'zoom-3c767',
    authDomain: 'zoom-3c767.firebaseapp.com',
    databaseURL: 'https://zoom-3c767-default-rtdb.firebaseio.com',
    storageBucket: 'zoom-3c767.appspot.com',
    measurementId: 'G-W25S1BEK4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQJw91D_i-zA4obm3GfzjRpaDoVetG5OA',
    appId: '1:481214437178:android:6a2fc71e900bae8f412203',
    messagingSenderId: '481214437178',
    projectId: 'zoom-3c767',
    databaseURL: 'https://zoom-3c767-default-rtdb.firebaseio.com',
    storageBucket: 'zoom-3c767.appspot.com',
  );
}
